# Generated by Django 3.0.6 on 2020-06-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('TRAVEL', 'TRAVEL'), ('MUSIC', 'MUSIC'), ('FASHION', 'FASHION')], default='FOOD', max_length=100),
            preserve_default=False,
        ),
    ]
